"use client";

import { useState, useEffect, useCallback } from "react";
import { apiFetch } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { GitBranch, GitPullRequest, Loader2, CheckCircle, Rocket } from "lucide-react";

interface Repo {
  id: number;
  fullName: string;
  name: string;
  private: boolean;
}

type Step = "repo" | "branch" | "push" | "pr" | "done";

export function PushToBranchDialog({
  open,
  onOpenChange,
  taskId,
  taskTitle,
  workspaceId,
  organizationId,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  taskId: string;
  taskTitle: string;
  workspaceId?: string;
  organizationId?: string;
}) {
  const [step, setStep] = useState<Step>("repo");
  const [repos, setRepos] = useState<Repo[]>([]);
  const [selectedRepo, setSelectedRepo] = useState<Repo | null>(null);
  const [branchName, setBranchName] = useState("");
  const [prTitle, setPrTitle] = useState(taskTitle);
  const [prBody, setPrBody] = useState(`Generated by Forge AI for task: ${taskTitle}`);
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [deployUrl, setDeployUrl] = useState<string | null>(null);
  const [deploying, setDeploying] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRepos = useCallback(async () => {
    setLoading(true);
    try {
      const res = await apiFetch<{ data: Repo[] }>("/git/repos");
      setRepos(res.data);
    } catch {
      setError("Failed to load repositories. Make sure GitHub is connected.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (open) {
      setStep("repo");
      setSelectedRepo(null);
      setBranchName(`forge/${taskTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40)}`);
      setPrTitle(taskTitle);
      setPrUrl(null);
      setDeployUrl(null);
      setError(null);
      fetchRepos();
    }
  }, [open, taskTitle, fetchRepos]);

  async function handlePush() {
    if (!selectedRepo) return;
    setError(null);
    setLoading(true);
    try {
      const [owner, repo] = selectedRepo.fullName.split("/");
      // Create branch
      await apiFetch(`/git/repos/${owner}/${repo}/branches`, {
        method: "POST",
        body: JSON.stringify({ name: branchName }),
      });
      // Push artifacts
      await apiFetch("/git/artifacts/push", {
        method: "POST",
        body: JSON.stringify({ owner, repo, branch: branchName, taskId }),
      });
      setStep("pr");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Push failed");
    } finally {
      setLoading(false);
    }
  }

  async function handleCreatePR() {
    if (!selectedRepo) return;
    setError(null);
    setLoading(true);
    try {
      const [owner, repo] = selectedRepo.fullName.split("/");
      const res = await apiFetch<{ data: { url: string } }>("/git/pr", {
        method: "POST",
        body: JSON.stringify({ owner, repo, title: prTitle, body: prBody, head: branchName }),
      });
      setPrUrl(res.data.url);
      setStep("done");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create PR");
    } finally {
      setLoading(false);
    }
  }

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={() => onOpenChange(false)} />
      <div className="relative z-50 w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-lg space-y-4">
        <div className="flex items-center gap-2">
          <GitBranch className="size-5 text-primary" />
          <h2 className="text-lg font-semibold">Push to GitHub</h2>
        </div>

        {error && (
          <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</div>
        )}

        {step === "done" ? (
          <div className="space-y-4">
            <div className="flex items-center gap-3 rounded-lg bg-primary/10 p-4">
              <CheckCircle className="size-5 text-primary shrink-0" />
              <div>
                <p className="text-sm font-medium">Pull request created!</p>
                <p className="text-xs text-muted-foreground mt-0.5">Branch: {branchName}</p>
              </div>
            </div>
            {prUrl && (
              <a href={prUrl} target="_blank" rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm text-primary hover:underline">
                <GitPullRequest className="size-4" /> View pull request on GitHub
              </a>
            )}
            {deployUrl && (
              <a href={deployUrl} target="_blank" rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm text-emerald-400 hover:underline">
                <Rocket className="size-4" /> View preview deployment
              </a>
            )}
            {workspaceId && organizationId && !deployUrl && (
              <Button
                variant="outline" className="w-full"
                disabled={deploying}
                onClick={async () => {
                  setDeploying(true);
                  try {
                    const res = await apiFetch<{ data: { url: string | null } }>("/deployments", {
                      method: "POST",
                      body: JSON.stringify({ organizationId, workspaceId, taskId, branch: branchName }),
                    });
                    if (res.data.url) setDeployUrl(res.data.url);
                  } catch (err) {
                    setError(err instanceof Error ? err.message : "Deploy failed");
                  } finally {
                    setDeploying(false);
                  }
                }}
              >
                {deploying
                  ? <><Loader2 className="size-4 animate-spin mr-2" />Deploying...</>
                  : <><Rocket className="size-4 mr-2" />Deploy to {"preview"}</>}
              </Button>
            )}
            <Button className="w-full" onClick={() => onOpenChange(false)}>Done</Button>
          </div>
        ) : step === "pr" ? (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Artifacts pushed to <span className="font-mono text-foreground">{branchName}</span>. Create a pull request?
            </p>
            <div className="grid gap-2">
              <Label>PR Title</Label>
              <Input value={prTitle} onChange={(e) => setPrTitle(e.target.value)} />
            </div>
            <div className="grid gap-2">
              <Label>Description</Label>
              <textarea
                className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm resize-none"
                value={prBody}
                onChange={(e) => setPrBody(e.target.value)}
              />
            </div>
            <div className="flex gap-3">
              <Button variant="outline" className="flex-1" onClick={() => onOpenChange(false)}>
                Skip
              </Button>
              <Button className="flex-1" onClick={handleCreatePR} disabled={loading}>
                {loading ? <Loader2 className="size-4 animate-spin mr-2" /> : <GitPullRequest className="size-4 mr-2" />}
                Create PR
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="grid gap-2">
              <Label>Repository</Label>
              {loading && repos.length === 0 ? (
                <p className="text-sm text-muted-foreground">Loading repositories...</p>
              ) : (
                <select
                  className="flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm"
                  value={selectedRepo?.fullName ?? ""}
                  onChange={(e) => {
                    const r = repos.find((r) => r.fullName === e.target.value) ?? null;
                    setSelectedRepo(r);
                  }}
                >
                  <option value="">Select repository...</option>
                  {repos.map((r) => (
                    <option key={r.id} value={r.fullName}>{r.fullName}</option>
                  ))}
                </select>
              )}
            </div>
            <div className="grid gap-2">
              <Label>Branch Name</Label>
              <Input
                value={branchName}
                onChange={(e) => setBranchName(e.target.value)}
                placeholder="forge/my-feature"
              />
            </div>
            <div className="flex gap-3">
              <Button variant="outline" className="flex-1" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button
                className="flex-1"
                onClick={handlePush}
                disabled={!selectedRepo || !branchName || loading}
              >
                {loading ? <Loader2 className="size-4 animate-spin mr-2" /> : <GitBranch className="size-4 mr-2" />}
                Push & Create Branch
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
