"use client";

import { useState } from "react";
import { CheckCircle, Loader2, AlertTriangle, DollarSign, FileCode, ListChecks } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";

interface PlanStep {
  order: number;
  agentType: string;
  description: string;
  status: string;
}

interface CostMeta {
  provider: string;
  model: string;
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  estimatedCost: number;
}

export interface ApprovalPayload {
  plan: { _id: string; steps: PlanStep[] };
  costMeta: CostMeta;
  taskTitle: string;
  taskId: string;
}

const AGENT_FILES: Record<string, string[]> = {
  backend: ["src/modules/**/*.ts", "src/core/**/*.ts"],
  frontend: ["src/components/**/*.tsx", "src/app/**/*.tsx"],
  testing: ["src/**/*.spec.ts", "src/**/*.test.ts"],
  reviewer: ["— (read-only review)"],
  planner: ["— (planning only)"],
};

export function ApprovalDialog({
  payload,
  onApprove,
  onCancel,
}: {
  payload: ApprovalPayload;
  onApprove: () => Promise<void>;
  onCancel: () => void;
}) {
  const [approving, setApproving] = useState(false);

  async function handleApprove() {
    setApproving(true);
    try {
      await onApprove();
    } finally {
      setApproving(false);
    }
  }

  const { plan, costMeta, taskTitle } = payload;
  const totalCostEstimate = costMeta.estimatedCost * plan.steps.length;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/60" onClick={onCancel} />
      <div className="relative z-50 w-full max-w-lg rounded-xl border border-border bg-card shadow-xl flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-start gap-3 p-5 border-b border-border shrink-0">
          <AlertTriangle className="size-5 text-amber-400 mt-0.5 shrink-0" />
          <div>
            <h2 className="text-base font-semibold">Review Execution Plan</h2>
            <p className="text-sm text-muted-foreground mt-0.5 truncate max-w-sm">{taskTitle}</p>
          </div>
        </div>

        <ScrollArea className="flex-1 min-h-0">
          <div className="p-5 space-y-5">
            {/* Steps */}
            <section>
              <div className="flex items-center gap-2 mb-3">
                <ListChecks className="size-4 text-muted-foreground" />
                <span className="text-sm font-medium">Execution Plan ({plan.steps.length} steps)</span>
              </div>
              <div className="space-y-2">
                {plan.steps.map((step) => (
                  <div key={step.order} className="flex items-start gap-3 rounded-lg border border-border/60 bg-muted/20 p-3">
                    <span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary mt-0.5">
                      {step.order + 1}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm leading-snug">{step.description}</p>
                      <Badge variant="outline" className="mt-1.5 text-[10px]">{step.agentType}</Badge>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Files to change */}
            <section>
              <div className="flex items-center gap-2 mb-3">
                <FileCode className="size-4 text-muted-foreground" />
                <span className="text-sm font-medium">Files to Change</span>
              </div>
              <div className="rounded-lg border border-border/60 bg-muted/20 p-3 space-y-1.5">
                {plan.steps.flatMap((step) => AGENT_FILES[step.agentType] ?? ["src/**/*"]).filter((v, i, a) => a.indexOf(v) === i).map((pattern) => (
                  <p key={pattern} className="font-mono text-xs text-muted-foreground">{pattern}</p>
                ))}
              </div>
            </section>

            {/* Diff preview */}
            <section>
              <div className="flex items-center gap-2 mb-3">
                <FileCode className="size-4 text-muted-foreground" />
                <span className="text-sm font-medium">Diff Preview</span>
              </div>
              <div className="rounded-lg border border-border/60 bg-black/30 p-3 font-mono text-[11px] text-muted-foreground space-y-0.5">
                <p className="text-green-400/70">+ Files will be generated by AI agents after approval</p>
                <p className="text-muted-foreground/50">+ Artifacts are stored and reviewable before any git push</p>
                <p className="text-muted-foreground/50">+ Use &quot;Push to GitHub&quot; in the Artifact Panel to push when ready</p>
              </div>
            </section>

            {/* Cost estimate */}
            <section>
              <div className="flex items-center gap-2 mb-3">
                <DollarSign className="size-4 text-muted-foreground" />
                <span className="text-sm font-medium">Estimated Cost</span>
              </div>
              <div className="rounded-lg border border-border/60 bg-muted/20 p-3 space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Provider / Model</span>
                  <span className="font-mono">{costMeta.provider} / {costMeta.model}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Planning tokens</span>
                  <span className="font-mono">{costMeta.totalTokens.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Est. execution tokens</span>
                  <span className="font-mono">~{(costMeta.totalTokens * plan.steps.length).toLocaleString()}</span>
                </div>
                <div className="border-t border-border/60 pt-2 flex justify-between text-sm font-semibold">
                  <span>Estimated total cost</span>
                  <span className="text-primary">${totalCostEstimate.toFixed(4)}</span>
                </div>
              </div>
            </section>
          </div>
        </ScrollArea>

        {/* Actions */}
        <div className="flex gap-3 p-5 border-t border-border shrink-0">
          <Button variant="outline" className="flex-1" onClick={onCancel} disabled={approving}>
            Cancel
          </Button>
          <Button className="flex-1" onClick={handleApprove} disabled={approving}>
            {approving
              ? <><Loader2 className="size-4 animate-spin mr-2" />Starting...</>
              : <><CheckCircle className="size-4 mr-2" />Approve &amp; Execute</>
            }
          </Button>
        </div>
      </div>
    </div>
  );
}
