"use client";

import { useEffect, useState, useCallback } from "react";
import { Package, Clock, GitBranch } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PushToBranchDialog } from "@/components/git/push-to-branch-dialog";

interface Artifact {
  _id: string;
  filename: string;
  language: string;
  content: string;
  agentId: { name: string; type: string };
  taskId: string;
  createdAt: string;
}

export function ArtifactPanel({ taskId, taskTitle }: { taskId?: string; taskTitle?: string }) {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [loading, setLoading] = useState(false);
  const [pushOpen, setPushOpen] = useState(false);

  const fetchArtifacts = useCallback(async () => {
    const id = taskId;
    if (!id) return;
    setLoading(true);
    try {
      const res = await apiFetch<{ data: Artifact[] }>(`/tasks/${id}/artifacts`);
      setArtifacts(res.data);
    } catch {
      setArtifacts([]);
    } finally {
      setLoading(false);
    }
  }, [taskId]);

  useEffect(() => {
    fetchArtifacts();
  }, [fetchArtifacts]);

  const getLangColor = (lang: string) => {
    if (lang === "typescript" || lang === "tsx") return "bg-blue-500/20 text-blue-400";
    if (lang === "markdown") return "bg-purple-500/20 text-purple-400";
    return "bg-muted text-muted-foreground";
  };

  return (
    <>
      <Card className="bg-card/40 border-border/50 flex flex-col h-[320px]">
      <CardHeader className="flex-row items-center justify-between pb-2 shrink-0">
        <CardTitle className="text-base font-semibold">Generated Files</CardTitle>
        <div className="flex items-center gap-2">
          {taskId && artifacts.length > 0 && (
            <Button size="sm" variant="outline" onClick={() => setPushOpen(true)}>
              <GitBranch className="size-3.5 mr-1" /> Push to GitHub
            </Button>
          )}
          <Package className="size-4 text-muted-foreground" />
        </div>
      </CardHeader>
      <CardContent className="flex-1 p-0 min-h-0">
        <ScrollArea className="h-full px-4">
          <div className="space-y-2 py-2">
            {loading ? (
              <p className="text-xs text-muted-foreground text-center py-4">Loading...</p>
            ) : artifacts.length === 0 ? (
              <p className="text-xs text-muted-foreground text-center py-4">
                {taskId ? "No artifacts yet. Execute a task to generate files." : "Select a task to view artifacts"}
              </p>
            ) : (
              artifacts.map((art) => (
                <div key={art._id} className="rounded-lg border border-border/50 p-3">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium truncate">{art.filename}</span>
                      <Badge variant="outline" className={`text-[10px] ${getLangColor(art.language)}`}>
                        {art.language}
                      </Badge>
                    </div>
                    <span className="flex items-center gap-1 text-[10px] text-muted-foreground">
                      <Clock className="size-3" />
                      {new Date(art.createdAt).toLocaleTimeString()}
                    </span>
                  </div>
                  <div className="bg-black/20 rounded p-2 font-mono text-[10px] text-muted-foreground max-h-24 overflow-y-auto">
                    <pre className="whitespace-pre-wrap">{art.content.slice(0, 300)}</pre>
                  </div>
                  {art.agentId && (
                    <p className="text-[10px] text-muted-foreground mt-1.5">
                      Generated by {art.agentId.name} ({art.agentId.type})
                    </p>
                  )}
                </div>
              ))
            )}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>

    {taskId && (
      <PushToBranchDialog
        open={pushOpen}
        onOpenChange={setPushOpen}
        taskId={taskId}
        taskTitle={taskTitle ?? "Forge task"}
      />
    )}
    </>
  );
}